from flask import Flask, render_template, request, jsonify
import cv2
import numpy as np
import pandas as pd
from datetime import datetime
import base64
import os
import json

app = Flask(__name__)

# ── Load label map from JSON (generated by train_model.py) ────
with open("label_map.json", "r") as f:
    raw = json.load(f)
    label_map = {int(k): v for k, v in raw.items()}

print(f"[INFO] Label map loaded: {label_map}")

# ── Load LBPH recognition model ───────────────────────────────
recognizer = cv2.face.LBPHFaceRecognizer_create()
recognizer.read("face_model.yml")

# ── Load DNN face detector ────────────────────────────────────
DNN_PROTO = "deploy.prototxt"
DNN_MODEL = "res10_300x300_ssd_iter_140000.caffemodel"
USE_DNN   = os.path.exists(DNN_PROTO) and os.path.exists(DNN_MODEL)

if USE_DNN:
    net = cv2.dnn.readNetFromCaffe(DNN_PROTO, DNN_MODEL)
    print("[INFO] Using DNN face detector ✅")
else:
    net  = None
    haar = cv2.CascadeClassifier(
        cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
    )
    print("[WARN] DNN files not found — using Haar cascade fallback")

# ═══════════════════════════════════════════════════════════════
#  FACE DETECTION
# ═══════════════════════════════════════════════════════════════

def detect_faces_dnn(img_bgr, conf_threshold=0.3):
    """
    DNN detector — works well for group/classroom photos.
    Tries at multiple scales so small/far faces are also found.
    Returns list of (x, y, w, h).
    """
    h, w  = img_bgr.shape[:2]
    found = {}   # use dict to deduplicate overlapping boxes

    # Try multiple input sizes — larger = better for small faces
    for input_size in [300, 600, 900]:
        blob = cv2.dnn.blobFromImage(
            cv2.resize(img_bgr, (input_size, input_size)),
            1.0,
            (input_size, input_size),
            (104.0, 177.0, 123.0)
        )
        net.setInput(blob)
        detections = net.forward()

        for i in range(detections.shape[2]):
            confidence = detections[0, 0, i, 2]
            if confidence < conf_threshold:
                continue

            box = detections[0, 0, i, 3:7] * np.array([w, h, w, h])
            x1, y1, x2, y2 = box.astype(int)

            # Clamp to image
            x1, y1 = max(0, x1), max(0, y1)
            x2, y2 = min(w, x2), min(h, y2)
            fw, fh  = x2 - x1, y2 - y1

            if fw < 20 or fh < 20:
                continue

            # Deduplicate: round to nearest 20px grid
            key = (round(x1 / 20), round(y1 / 20))
            if key not in found or found[key][4] < confidence:
                found[key] = (x1, y1, fw, fh, confidence)

    return [(x, y, fw, fh) for x, y, fw, fh, _ in found.values()]


def detect_faces_haar(gray):
    """Fallback Haar cascade detector."""
    gray_eq = cv2.equalizeHist(gray)
    faces   = haar.detectMultiScale(gray_eq, 1.05, 3, minSize=(30, 30))
    if not isinstance(faces, np.ndarray):
        return []
    return faces.tolist()


# ═══════════════════════════════════════════════════════════════
#  ATTENDANCE HELPERS
# ═══════════════════════════════════════════════════════════════

def mark_attendance(name):
    """Mark student Present — only once per day."""
    today = datetime.now().strftime("%d-%m-%Y")
    time  = datetime.now().strftime("%I:%M %p")
    try:
        df = pd.read_csv("attendance.csv")
        if not df[(df["Name"] == name) & (df["Date"] == today)].empty:
            return False   # already marked today
    except Exception:
        pass
    with open("attendance.csv", "a") as f:
        f.write(f"{name},{time},{today},Present\n")
    return True


def img_to_base64(img_bgr):
    """Convert OpenCV image → base64 JPEG string."""
    _, buffer = cv2.imencode('.jpg', img_bgr, [cv2.IMWRITE_JPEG_QUALITY, 88])
    return "data:image/jpeg;base64," + base64.b64encode(buffer).decode('utf-8')


# ═══════════════════════════════════════════════════════════════
#  ROUTES
# ═══════════════════════════════════════════════════════════════

@app.route('/')
def index():
    return render_template("index.html", students=list(label_map.values()))


@app.route('/api/students')
def get_students():
    return jsonify({"students": list(label_map.values()), "count": len(label_map)})


@app.route('/api/attendance')
def get_attendance():
    today = datetime.now().strftime("%d-%m-%Y")
    records, today_count = [], 0
    try:
        df = pd.read_csv("attendance.csv")
        df.columns = ["Name", "Time", "Date", "Status"]
        records     = df.iloc[::-1].to_dict(orient="records")
        today_count = len(df[df["Date"] == today])
    except Exception:
        pass
    return jsonify({"records": records, "today_count": today_count, "total": len(records)})


@app.route('/api/reset_attendance', methods=['POST'])
def reset_attendance():
    with open("attendance.csv", "w") as f:
        f.write("Name,Time,Date,Status\n")
    return jsonify({"success": True, "message": "Attendance records cleared."})


@app.route('/api/upload', methods=['POST'])
def upload():
    # ── Validate ──────────────────────────────────────────────
    if 'image' not in request.files:
        return jsonify({"success": False, "error": "No image provided."}), 400

    file       = request.files['image']
    file_bytes = np.frombuffer(file.read(), np.uint8)
    img        = cv2.imdecode(file_bytes, cv2.IMREAD_COLOR)

    if img is None:
        return jsonify({"success": False, "error": "Could not decode image."}), 400

    # ── Resize very large images (keep aspect ratio) ──────────
    h, w = img.shape[:2]
    if max(h, w) > 1400:
        scale = 1400 / max(h, w)
        img   = cv2.resize(img, (int(w * scale), int(h * scale)))

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # ── Detect faces ──────────────────────────────────────────
    if USE_DNN:
        # conf_threshold=0.3 catches small/far faces too
        faces = detect_faces_dnn(img, conf_threshold=0.3)
    else:
        faces = detect_faces_haar(gray)

    print(f"[INFO] Faces detected: {len(faces)}")

    results = []

    for (x, y, fw, fh) in faces:
        # ── Crop & preprocess face ROI ────────────────────────
        face_roi = gray[y:y+fh, x:x+fw]
        face_roi = cv2.resize(face_roi, (200, 200))
        face_roi = cv2.equalizeHist(face_roi)   # must match training

        label, confidence = recognizer.predict(face_roi)

        # ── LBPH threshold ────────────────────────────────────
        # Lower confidence = better match (0 is perfect)
        # 100 works for most cases; raise to 120 if too strict
        THRESHOLD = 100
        if confidence < THRESHOLD:
            name = label_map.get(label, "Unknown")
        else:
            name = "Unknown"

        print(f"  → Label: {label} | Name: {name} | Confidence: {confidence:.1f}")

        is_new = False
        if name != "Unknown":
            is_new = mark_attendance(name)

        results.append({
            "name":       name,
            "status":     "Present" if name != "Unknown" else "Unknown",
            "is_new":     is_new,
            "confidence": round(float(confidence), 1)
        })

        # ── Draw bounding box & label ─────────────────────────
        if name == "Unknown":
                continue          # ← don't draw box for strangers

        color = (0, 255, 120)
        cv2.rectangle(img, (x, y), (x+fw, y+fh), color, 2)

        label_text     = f" {name} ({round(confidence)}) "
        (tw, th), _    = cv2.getTextSize(label_text, cv2.FONT_HERSHEY_DUPLEX, 0.55, 1)
        cv2.rectangle(img, (x, y - th - 10), (x + tw + 4, y), color, -1)
        cv2.putText(img, label_text, (x + 2, y - 5),
                    cv2.FONT_HERSHEY_DUPLEX, 0.55, (255, 255, 255), 1)

    return jsonify({
        "success":         True,
        "results":         results,
        "annotated_image": img_to_base64(img),
        "faces_detected":  len(faces),
        "recognized":      sum(1 for r in results if r["name"] != "Unknown")
    })


@app.route('/video_feed')
def video_feed():
    return "Camera not enabled", 200

@app.route('/api/camera/start', methods=['POST'])
def camera_start():
    return jsonify({"success": False, "message": "Camera not enabled."})

@app.route('/api/camera/stop', methods=['POST'])
def camera_stop():
    return jsonify({"success": True})


# ═══════════════════════════════════════════════════════════════
#  ENTRY POINT
# ═══════════════════════════════════════════════════════════════

if __name__ == "__main__":
    if not os.path.exists("attendance.csv"):
        with open("attendance.csv", "w") as f:
            f.write("Name,Time,Date,Status\n")

    print("=" * 50)
    print("  AI Attendance System")
    print(f"  Detector : {'DNN ✅' if USE_DNN else 'Haar (fallback)'}")
    print(f"  Students : {list(label_map.values())}")
    print("  Open     : http://localhost:5000")
    print("=" * 50)
    app.run(debug=True)